name: '@shopify/polaris CI'

on:
  pull_request:
    paths:
      - 'polaris-react/**'
  push:
    branches: [main, polaris-release]
    paths:
      - 'polaris-react/**'

jobs:
  accessibility_test:
    name: 'Accessibility test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.0.0
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - uses: actions/cache@v2
        name: Restore internal build cache
        with:
          path: |
            **/.turbo
            node_modules/.cache/turbo
            polaris-react/build-internal/cache
          key: ${{ runner.os }}-node${{ matrix.node-version }}-accessibility-test-v1-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-node${{ matrix.node-version }}-accessibility-test-v1-

      - run: pnpm --frozen-lockfile
      - run: pnpm build
      - run: pnpm --filter "@shopify/polaris" run storybook:build --quiet
      - run: node ./polaris-react/scripts/accessibility-check.js
        env:
          STORYBOOK_DISABLE_DOCS: 1

  visual_regression_test:
    name: 'Visual regression test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Chromatic git history to track changes
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - uses: actions/cache@v2
        name: Restore internal build cache
        with:
          path: |
            **/.turbo
            node_modules/.cache/turbo
            polaris-react/build-internal/cache
          key: ${{ runner.os }}-node${{ matrix.node-version }}-visual-regression-test-v1-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-node${{ matrix.node-version }}-visual-regression-test-v1-

      - run: pnpm
      - run: pnpm build
      - run: pnpm --filter "@shopify/polaris" storybook:build --quiet

      - uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: 'main'
          storybookBuildDir: 'polaris-react/build-internal/storybook/static'
          exitZeroOnChanges: true
          exitOnceUploaded: true
