name: CI

on:
  push:
    branches: [main, polaris-release]
  pull_request:

jobs:
  build:
    name: 'Validate with Node v${{ matrix.node_version }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['14.17.0', '16.13.0']
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.0.0

      - name: Setup Node with v${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node_version: ${{ matrix.node_version }}
          cache: pnpm

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            **/*.tsbuildinfo
            **/.turbo
            node_modules/.cache/turbo
          key: ${{ runner.os }}-node${{ matrix.node_version }}-test-v1-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-node${{ matrix.node_version }}-test-v1-

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Type check
        run: pnpm type-check

      - name: Test
        run: pnpm test
